name: CDK

on:
  pull_request:
    paths:
      - "**.ts"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/cdk-integ.yml"
  push:
    branches:
      - main

concurrency:
  group: cdk-integ-groug
  cancel-in-progress: false

jobs:
  integ:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    env:
      HUSKY: 0
      FORCE_COLOR: 2
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::676824148681:role/github-actions-role
          aws-region: eu-west-1
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
        env:
          HUSKY: 0
      - run: npm run cdk-integ -- --force --disable-update-workflow
