name: Lint

on:
  pull_request:
    paths:
      - "**.ts"
      - "**.md"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/lint.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      HUSKY: 0
      FORCE_COLOR: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: npm

      - run: npm ci
        env:
          HUSKY: 0

      - run: npx eslint "src/**/*.ts"
      - run: npx prettier --check "*.{ts,md}"
      - run: npx cspell "**/*.{ts,md}"
